### PR TITLE
Fixed max-height issue

### PR DESCRIPTION
**Pull request by georgek901**
It fixes the issue of https://github.com/DominikSerafin/vuebar/isses/30) with flexbox

### CODE REVIEW

**Comment by martinsnajdr** [comment]
This PR should be accepted. Not working max-height is a dealbreaker, because most of the time you specify max-height, so if the element is not bigger than (n)px, the scrollbar is not visible. With height only working you have to have fixed height.

**Comment by DominikSerafin** [comment]
Hey @martinsnajdr, I'll look into merging this into Vuebar 2.0. Vuebar 1.0 is kinda freezed right now and I don't think I'll be pushing any new updates for it due to limited time I have to work on open source. 

2.0 is almost ready, I just need to make some last polishes, etc., but again - I didn't have time to do that in recent months. 

If you're interested or adventurous, you can check it on `development` branch.

**Comment by iambaboon** [comment]
Hey @DominikSerafin. We are using your directive in our project which needs horizontal scroller and setting minimum and maximum dragger height. I can see you have introduced it in 2.0 and you said it is going to be released soon. Can we expect your release until the end of September? If not what would be the best workaround to find those features as soon as possible?
Thanks for your answers and for your amazing directive!

**Comment by DominikSerafin** [comment]
@iambaboon I don't think I'll be able to release 2.0 by the end of September. As for workaround I can suggest taking out the WIP Vuebar 2.0 from "development" branch and using that code. It's pretty usable already when it comes to horizontal scrolling. The only disadvantages are that it's undocumented & unstable (API/design might change in future). But there are plenty of demos in the index.html file.

**Comment by DominikSerafin** [comment]
https://github.com/DominikSerafin/vuebar/issues/84

**Pull request closed without merging**
